-- This has to be first or else nothing will work
require("usr.lazyManager")
require("usr.core")

require("usr.alpha")
require("usr.annotations")
require("usr.autopairs")
require("usr.buffline")
require("usr.cmp")
require("usr.comment")
require("usr.copilot")
require("usr.DAP")
require("usr.gitsigns")
require("usr.illuminate")
require("usr.impatient")
require("usr.lsp")
require("usr.lualine")
require("usr.navigation")
require("usr.project")
require("usr.refactoring")
require("usr.todo-comments")
require("usr.toggleterm")
require("usr.trouble")
require("usr.ts")
require("usr.tscope")
