local pluginLoader = require("usr.core.loader.load")

pluginLoader:load_configs({
	"usr.core",

	"usr.alpha",
	"usr.annotations",
	"usr.autopairs",
	"usr.buffline",
	"usr.chatai",
	"usr.cmp",
	"usr.comment",
	"usr.DAP",
	"usr.gitsigns",
	"usr.illuminate",
	"usr.impatient",
	"usr.indentation",
	"usr.lsp",
	"usr.lualine",
	"usr.navigation",
	"usr.plugins",
	"usr.project",
	"usr.refactoring",
	"usr.todo-comments",
	"usr.toggleterm",
	"usr.trouble",
	"usr.ts",
	"usr.tscope",
	"usr.alpha",
	"usr.WinBar",
})
