require("usr.alpha")
require("usr.autopairs")
require("usr.annotations")
require("usr.buffline")
require("usr.cmp")
require("usr.comment")
require("usr.copilot")
require("usr.core")
require("usr.gitsigns")
require("usr.illuminate")
require("usr.impatient")
require("usr.indentation")
require("usr.lsp")
require("usr.lualine")
require("usr.nvim-tree")
require("usr.plugins")
require("usr.refactoring")
require("usr.satellite")
require("usr.scroll")
require("usr.toggleterm")
require("usr.todo-comments")
require("usr.trouble")
require("usr.tscope")
require("usr.ts")

require("usr.DAP")

