-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
return {
	kind = {
		-- Module = "",
		-- Variable = "",
		--[[ Constructor = "", ]]
		--[[ Function = "", ]]
		--[[ Keyword = "", ]]
		--[[ Method = "", ]]
		--[[ Snippet = "", ]]
		Class = "",
		Color = "",
		Constant = "",
		Constructor = "",
		Container = "",
		Enum = "",
		EnumMember = "",
		Event = "",
		Field = "",
		File = "",
		Folder = "",
		Function = "",
		Interface = "",
		Keyword = "",
		Method = "m",
		Module = "",
		Namespace = "",
		Operator = "",
		Property = "",
		Reference = "",
		Snippet = "",
		Struct = "",
		Text = "",
		TypeParameter = "",
		Unit = "",
		Value = "",
		Variable = "",
	},
	type = {
		Array = "",
		Boolean = "蘒",
		NullName = "[]",
		Number = "",
		Object = "",
		String = "",
	},
	documents = {
		File = "",
		Files = "",
		Folder = "",
		OpenFolder = "",
	},
	git = {
		Add = "",
		Diff = "",
		Ignore = "",
		Mod = "",
		Remove = "",
		Rename = "",
		Repo = "",
	},
	ui = {
		-- ChevronRight = "",
		ArrowClosed = "",
		ArrowOpen = "",
		BigCircle = "",
		BigUnfilledCircle = "",
		BookMark = "",
		Bug = "",
		Calendar = "",
		Check = "",
		ChevronRight = ">",
		Circle = "",
		Close = "",
		CloudDownload = "",
		Code = "",
		Comment = "",
		Dashboard = "",
		Fire = "",
		Gear = "",
		History = "",
		Home = "﫷",
		Lightbulb = "",
		List = "",
		Lock = "",
		NewFile = "",
		Note = "",
		Package = "",
		Pencil = "",
		Project = "",
		Search = "",
		SignIn = "",
		SignOut = "",
		Table = "",
		Telescope = "",
		Test = "⏲ ",
	},
	diagnostics = {
		Error = "",
		Hint = "",
		Information = "",
		Question = "",
		Warning = "",
	},
	misc = {
		Robot = "ﮧ",
		Squirrel = "",
		Tag = "",
		Watch = "",
	},
	dap = {
		Pause = "",
		Play = "",
		RunLast = "ﬀ",
		StepBack = "",
		StepInto = "",
		StepOut = "",
		StepOver = "",
		Terminate = "",
	}
}
