-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
return {
	kind = {
		Call = " ",
		Color = " ",
		Constant = " ",
		Constructor = " ",
		Container = " ",
		Continue = '→ ',
		Copilot = ' ',
		Declaration = " ",
		Delete = "󰚃 ",
		Event = " ",
		Field = " ",
		Function = "󰡱 ",
		Interface = " ",
		Keyword = " ",
		Method = "m ",
		Module = " ",
		Operator = " ",
		Property = " ",
		Settings = " ",
		Quit = "󰩈 ",
		RecentlyUsed = "󱦺 ",
		Reference = " ",
		Sleep = "󰒲 ",
		Snippet = " ",
		Text = "󰊄 ",
		Type = "󰉺 ",
		TextLines = " ",
		TypeParameter = " ",
		Unit = " ",
		Unnamed = "󰺴 ",
		Value = " ",
		Variable = " ",
	},
	type = {
		Array = " ",
		Boolean = "󱎅 ",
		Case = "󱓡 ",
		Class = " ",
		Do = " ",
		Enum = " ",
		EnumMember = " ",
		For = " ",
		If = "󰊴 ",
		Namespace = " ",
		NullName = "[] ",
		Number = " ",
		Null = "󰚃 ",
		Object = " ",
		Repeat = " ",
		String = " ",
		Struct = " ",
		Switch = "󰔡 ",
		While = " ",
	},
	documents = {
		File = " ",
		Files = " ",
		EmptyFolder = " ",
		FullFolder = " ",
		OpenFolder = " ",
		OpenFullFolder = "",
		RecentFile = " ",
		Symlink = " ",
	},
	git = {
		Add = " ",
		BoldBar = "▎",
		Branch = " ",
		ChagneDeleted = "~",
		Deleted = "󰗩 ",
		Diff = " ",
		Ignore = " ",
		Ignored = "◌ ",
		Mod = "● ",
		Remove = " ",
		Rename = " ",
		Renamed = "➜",
		Repo = " ",
		Restore = " ",
		Staged = " ",
		TopDeleted = '‾',
		Unmerged = " ",
		Unstaged = " ",
		Untracked = "┆ ",
	},
	ui = {
		ArrowClosed = " ",
		ArrowOpen = " ",
		BigCircle = " ",
		BigUnfilledCircle = " ",
		BookMark = " ",
		Bug = " ",
		Calendar = " ",
		Check = "󰄬 ",
		ChevronRight = "> ",
		Circle = " ",
		Close = " ",
		CloudDownload = " ",
		Code = " ",
		Comment = " ",
		Configuration = " ",
		Dashboard = " ",
		Do = " ",
		Extends = '… ',
		File = " ",
		Fire = " ",
		Gear = " ",
		History = " ",
		Home = " ",
		Indicator = " ",
		LeftMarker = " ",
		LeftSeparator = "",
		Lightbulb = " ",
		List = " ",
		Lock = " ",
		NewFile = " ",
		Note = "󰎞 ",
		Operator = " ",
		Package = " ",
		Pencil = " ",
		Project = " ",
		Regex = ' ',
		RightMarker = " ",
		RightSeparator = "",
		Search = " ",
		Separator = ' ',
		SignIn = " ",
		SignOut = " ",
		Table = " ",
		Telescope = " ",
		Test = "󰙨 ",
	},
	diagnostics = {
		Lsp = ' ',
		Error = " ",
		Hint = " ",
		Information = " ",
		Question = " ",
		Warning = " ",
	},
	misc = {
		Robot = "󱨚 ",
		Squirrel = " ",
		Tag = " ",
		Watch = " ",
	},
	dap = {
		Pause = "󰏤 ",
		Play = " ",
		RunLast = "󰘁 ",
		StepBack = " ",
		StepInto = " ",
		StepOut = "󰆸 ",
		StepOver = " ",
		Terminate = "󰅜 ",
	},
	telescope = {
		Prompt = " ",
		Selection = " ",
	},
	system = {
		Apple = " ",
		Linux = " ",
		Windows = " ",
	},
	possition = {
		Pos1 = "__",
		Pos2= "▁▁",
		Pos3= "▂▂",
		Pos4= "▃▃",
		Pos5= "▄▄",
		Pos6= "▅▅",
		Pos7= "▆▆",
		Pos8= "▇▇",
		Pos9= "██",
	},
	access = {
		ReadOnly = " ",

	}
}
