-- copilot.lua
--
-- Copilot is a plugin that provides autocompletion for nvim.
-- It is a wrapper around the copilot binary.
-- 		generated by Copilot
-- remaps <C-a> to accept the suggestion
vim.cmd([[ imap <silent><script><expr> <C-a> copilot#Accept("\<CR>")]])
vim.g.copilot_no_tab_map = true
